version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  app:
    build: .
    container_name: app
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb+srv://dat012:haikhongkhonghai@cluster0.6uhqt.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      PORT: 5000
    depends_on:
      - mongo